GET http://localhost:3001/api/dashboard
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VybmFtZSIsInNjb3BlIjoic3RhbmRhcmQiLCJpYXQiOjE3NTM1ODM0MDYsImV4cCI6MTc1MzU4MzQzNn0.4qGLqWjyFJm4jkpnLJ0dqgyhaRnHJ_Zj4dEtwcLoq18; refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VybmFtZSIsInNjb3BlIjoic3RhbmRhcmQiLCJpYXQiOjE3NTM1ODM0MDYsImV4cCI6MTc1MzU4NzAwNn0.sg3vRhYPP1sN6D2O4CTj3ldHoatvxbTarTtXz4uHpmY;